Added basic CLI functionality based on click module.
Future-House/paper-qa pull request #74
Opened 2023-04-17 07:31 UTC by malekinho8

Added a method to Docs object that allows user to enter 'chat' mode, which is basically just query on an infinite loop. Reflected changes in setup.py to allow for easy installation. Updated README.md to include a Usage example.

I tried to implement changes based on your suggestion, but not 100% sure if I did everything right. For now I put `cli.py` in the `paperqa.contrib` folder which houses the code to enter into chat mode with the Docs object from the CLI. LMK your thoughts/next steps whenever you get a chance!

2023-04-18 13:04 UTC, MilesCranmer commented
Good idea. Might be nice to allow an arbitrary number of arguments? Then one could combine with shell globbing, like:

```
paperqa my_pdfs/**/*.pdf
```

2023-04-21 20:54 UTC, whitead requested changes

2023-04-21 20:54 UTC, whitead commented on paperqa/docs.py
> +    def chat(self):
Let's move this to CLI, and not call it `chat`, since there is no memory of the conversation

2023-04-21 20:54 UTC, whitead commented on paperqa/cli.py
> +        if len(sys.argv) == 2:
The click module supports glob filepaths I believe, let's use that instead

2023-04-21 20:54 UTC, whitead commented on paperqa/cli.py
> +    if answer == PDF_URL:
Can we just remove this for now?

2024-09-11 17:03 UTC, jamesbraza commented
Hello @malekinho8 thank you for this PR. Version 5 (just released) ships with a CLI, so I am going to close this out.

We appreciate your help and please feel free to continue opening PRs oriented towards the new CLI

2024-09-11 17:03 UTC, closed without merging